name = "agx_debug"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 2.3.2 and < 3.0.0"

[tools.lustre.html]
title = "agx debug"
links = [
  { rel = "icon", href = "/favicon.png", type = "image/png" }
]
